---
version: "3"
services:
  db: 
    image: devarajyothi/mypyapp:dbimage
    ports:
     - "3306:3306"
    deploy:
      replicas: 4
  auth_service:
    image: devarajyothi/mypyapp:authimage
    ports:
     - "5001:5001"
    deploy:
      replicas: 3
  book_service:
    image: devarajyothi/mypyapp:bookimage
    ports:
     - "5002:5002"
    deploy:
      replicas: 3
  borrow_service:
    image: devarajyothi/mypyapp:borrowhimage
    ports:
      - "5003:5003"
    deploy:
      replicas: 3
 frontend:
    image: devarajyothi/mypyapp:authimage
    ports:
      - "5000:5000"
    deploy:
      replicas: 3
  
    
