version: "3.8"

services:
  db:
    image: devarajyothi/mypyapp:dbimage
    ports:
      - "3306:3306"
    deploy:
      replicas: 4
    networks:
      - dbnetwork
      - appnetwork

  auth_service:
    image: devarajyothi/mypyapp:authimage
    ports:
      - "5001:5001"
    deploy:
      replicas: 3
    networks:
      - appnetwork
      - dbnetwork

  book_service:
    image: devarajyothi/mypyapp:bookimage
    ports:
      - "5002:5002"
    deploy:
      replicas: 3
    networks:
      - appnetwork
      - dbnetwork

  borrow_service:
    image: devarajyothi/mypyapp:borrowimage
    ports:
      - "5003:5003"
    deploy:
      replicas: 3
    networks:
      - appnetwork
      - dbnetwork

  frontend:
    image: devarajyothi/mypyapp:frontendimage
    ports:
      - "5000:5000"
    deploy:
      replicas: 3
    networks:
      - appnetwork
      - dbnetwork
    depends_on:
      - "db"

networks:
  appnetwork:
    driver: overlay
  dbnetwork:
    driver: overlay
